const assert = require("node:assert/strict");
require("../../src/claude_launcher/web/static/session-tabs.js");
const values = new Map();
const storage = { getItem: k => values.get(k), setItem: (k, v) => values.set(k, v) };
const tabs = new SessionTabHistory(storage, "tabs", ["p1", "p2"]);
for (const name of ["a", "b", "c", "d", "e"]) tabs.visit(name);
tabs.visit("a");
assert.deepEqual(tabs.names(), ["p1", "p2", "a", "b", "c", "d", "e"], "visiting preserves display order");
tabs.visit("f");
assert.deepEqual(tabs.names(), ["p1", "p2", "a", "c", "d", "e", "f"], "LRU eviction excludes pins");
tabs.syncPins(["p1", "p2", "a"]);
tabs.visit("g");
assert.deepEqual(tabs.names(), ["p1", "p2", "a", "c", "d", "e", "f", "g"]);
tabs.visit("a");
tabs.syncPins(["p1", "p2"]);
assert.deepEqual(tabs.names(), ["p1", "p2", "a", "d", "e", "f", "g"], "unpin applies recent cap");
assert.deepEqual(new SessionTabHistory(storage, "tabs", ["p1", "p2"]).names(), tabs.names(), "reload preserves order");
tabs.close("a");
assert.equal(tabs.latest(), "g");
assert(!new SessionTabHistory(storage, "tabs", ["p1", "p2"]).names().includes("a"), "closed tabs stay closed");
assert.deepEqual(new SessionTabHistory(storage, "other-daemon").names(), [], "storage scopes are independent");
const manyPins = Array.from({ length: 8 }, (_, i) => `p${i}`);
const unlimitedPins = new SessionTabHistory(storage, "many-pins", manyPins);
for (let i = 0; i < 7; i++) unlimitedPins.visit(`recent${i}`);
assert.equal(unlimitedPins.names().length, 13, "eight pins and five recent tabs coexist");
values.set("bad", '{invalid');
assert.deepEqual(new SessionTabHistory(storage, "bad", ["p"]).names(), ["p"]);
values.set("bad", JSON.stringify([null, {}, { name: "x", used: -1 }, { name: "ok", used: 1 }, { name: "ok", used: 2 }]));
assert.deepEqual(new SessionTabHistory(storage, "bad").names(), ["ok"]);
const denied = { getItem() { throw Error("denied"); }, setItem() { throw Error("denied"); } };
const ephemeral = new SessionTabHistory(denied, "tabs");
ephemeral.visit("a");
assert.deepEqual(ephemeral.names(), ["a"]);
console.log("sessiontabs_check: ok");
