"""``await-landing``: a silent parent must not park a round forever.

The wait used to have three options -- ``landed``, ``rebase``, ``remeasure``
-- and a fourth outcome nobody declared. Its prompt said "if none of the
three, do not choose and stay", so a parent that never answered left the
round standing with no upper bound, and the three things that produce that
silence (the request dropped from a batch, the parent not having read its
table yet, the parent session gone) all looked identical from here.

Two edges close it, and these tests pin both.

``nudge`` is the default branch when no answer has arrived: it carries
``interval: 600``, so the engine HOLDS a take inside ten minutes rather than
refusing it (``waiting_window``), the daemon's ``WindowClock`` releases it and
wakes the session, and the run walks ``await-landing -> landing-nudge ->
await-landing``. The clock is outside the agent, which is the whole point --
the old wait had nothing but the parent's answer to wake it.

``declined`` is the answer the graph never had. It routes to
``landing-declined`` (settle the refusal on the board, unfreeze the branch),
then to ``rework-gate`` -- a HUMAN gate, no ``from`` -- and only past that
back to ``work``. The gate is not decoration: that edge is the only one in
the workflow that winds a round backwards, and an automatic rewind makes
"declined -> rework -> same decline" a loop nobody sees.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from claude_launcher.cflow import engine, model, state as state_mod

ROOT = Path(__file__).resolve().parents[1]
PROJECT_OVERRIDES = ROOT / ".claunch" / "workflows"

#: The cadence the wait declares, in seconds. Ten minutes is two of the
#: leader's 300s integration windows: a nudge landing inside one window would
#: push the same row back at a parent that has not been able to close the
#: batch yet, which spends the parent's turn instead of buying anything.
NUDGE_INTERVAL = 600.0


def _layers():
    """The bundled worker and this repository's project copy of it.

    Both are pinned because the project copy is what actually runs here and
    is regenerated by ``tools/sync_project_layer.py`` -- a canonical edit that
    was never synced would otherwise pass every test in this file.
    """
    yield "bundled", state_mod.load_bundled("improv-worker")
    yield "project", model.load(PROJECT_OVERRIDES / "improv-worker.yaml")


def _prose(text) -> str:
    return " ".join((text or "").split())


# --------------------------------------------------------------------------- #
# the nudge edge
# --------------------------------------------------------------------------- #
def test_the_wait_offers_a_paced_nudge_that_returns_to_the_wait():
    for label, wf in _layers():
        wait = wf.steps["await-landing"]
        assert wait.select is not None, f"{label}: await-landing is a select"
        nudge = wait.select.options.get("nudge")
        assert nudge is not None, (
            f"{label}: the wait needs a branch for 'no answer yet' -- without "
            "one its only instruction for silence is to keep standing"
        )
        assert nudge.interval == NUDGE_INTERVAL, (
            f"{label}: the nudge is paced at {NUDGE_INTERVAL:g}s; without an "
            "interval the agent would decide the cadence itself every turn"
        )
        assert nudge.next == "landing-nudge"
        assert wf.steps["landing-nudge"].next == "await-landing", (
            f"{label}: the nudge step must return to the wait, or the round "
            "leaves the place it is supposed to be waiting in"
        )


def test_the_nudge_step_changes_nothing_it_is_waiting_on():
    """A reminder is a signal, not a state change.

    The branch stays frozen (the request was filed against that tip) and the
    board gets no new comment -- the evidence bundle is already one comment
    from ``integration-request``, and n reminder comments on the same issue
    make the next reader separate the verdict from the noise.
    """
    for label, wf in _layers():
        rules = _prose(wf.steps["landing-nudge"].instructions)
        for anchor in ("동결은 그대로다", "보드에 코멘트를 새로 쌓지 않는다",
                       "요청을 다시 만들지 않는다"):
            assert anchor in rules, f"{label}: landing-nudge lost {anchor!r}"
        # What makes the second line worth reading: the value that moved.
        assert "몇 번째 재촉" in rules
        # A parent that cannot be reached IS the answer, and is reported.
        assert "상위 세션 종료" in rules


def test_a_nudge_is_held_inside_its_window_and_released_by_the_clock(
    proj_wait, clock
):
    """The behaviour, not the declaration: take, return, take again, held.

    The distilled workflow below has the same three parts as the real wait --
    a paced option, a step that loops back, and a plain exit -- so the engine
    path under test is the one ``await-landing`` uses.
    """
    engine.start("waiter")
    # First take: nothing to pace against, so it goes through immediately.
    payload = engine.select("nudge", "no answer yet")
    assert (payload["status"], payload["step_id"]) == ("step", "nudge-step")
    engine.report("nudged the parent, 1st")
    back = engine.next_step()
    assert back["step_id"] == "wait", "the nudge step returns to the wait"

    # Second take, a minute later: held, not refused.
    clock(60)
    held = engine.select("nudge", "still no answer")
    assert held["status"] == "waiting_window"
    assert held["opens_at"] == (T0 + timedelta(seconds=NUDGE_INTERVAL)).isoformat(
        timespec="seconds"
    )
    assert held["remaining"] == int(NUDGE_INTERVAL) - 60
    assert "do not poll" in held["note"]
    assert state_mod.load_state()["current"] == "wait", "the run has not moved"

    # The window opens; the run moves on its own and the session is woken.
    clock(NUDGE_INTERVAL - 60)
    released = engine.next_step()
    assert (released["status"], released["step_id"]) == ("step", "nudge-step")


def test_an_answer_arriving_mid_hold_cancels_the_nudge(proj_wait, clock):
    """Holding is not committing. The parent's answer wins whenever it lands."""
    engine.start("waiter")
    engine.select("nudge", "no answer yet")
    engine.report("nudged")
    engine.next_step()
    clock(60)
    assert engine.select("nudge", "still nothing")["status"] == "waiting_window"
    landed = engine.select("landed", "merge notice arrived")
    assert (landed["status"], landed["step_id"]) == ("step", "landed")
    assert state_mod.load_state().get("window") is None


# --------------------------------------------------------------------------- #
# the declined edge
# --------------------------------------------------------------------------- #
def test_a_refusal_has_a_declared_route_of_its_own():
    """Before this, a refusal reached ``wrapup`` only by a person typing
    ``claunch cflow goto`` -- an undeclared transition hand-made per round.
    The round that was refused and means to fix and retry had no route at
    all, and that is the common case."""
    for label, wf in _layers():
        declined = wf.steps["await-landing"].select.options.get("declined")
        assert declined is not None, (
            f"{label}: 'the parent said no' is an answer and needs an edge"
        )
        assert declined.interval is None, (
            f"{label}: a refusal is not paced -- it is acted on once"
        )
        assert declined.next == "landing-declined"
        assert wf.steps["landing-declined"].next == "rework-gate"


def test_the_refusal_is_settled_before_the_gate_not_after():
    """The board is put right first, then the human is asked.

    Settling behind the gate would leave the issue sitting in ``in_review``
    for as long as the approval takes -- a row in the parent's table that
    nobody is pushing.
    """
    for label, wf in _layers():
        settle = wf.steps["landing-declined"]
        assert settle.ask is None, (
            f"{label}: landing-declined settles; the gate is the next step"
        )
        rules = _prose(settle.instructions)
        assert "--status in_progress" in rules, f"{label}: issues come back"
        assert "DECLINED:" in rules, f"{label}: the refusal is journalled on the board"
        assert "동결을 푼다" in rules
        # A refusal is not a licence to land it yourself.
        assert "master는 여전히 건드리지 않는다" in rules


def test_rework_resumes_only_through_a_human_gate():
    for label, wf in _layers():
        gate = wf.steps["rework-gate"]
        assert gate.ask is not None, (
            f"{label}: rewinding a round to 'work' is the user's call"
        )
        assert gate.ask.delegate.candidates == [], (
            f"{label}: no delegation -- the parent that just refused this "
            "branch must not also decide whether it is reworked"
        )
        assert gate.ask.delegate.timeout is None, (
            f"{label}: no timeout; a gate that opens on its own restores the "
            "unbounded loop it was added to stop"
        )
        assert gate.next == "work", f"{label}: past the gate, the round reworks"
        assert gate.ask.on_decline == "landing-declined-hold"
        assert wf.steps["landing-declined-hold"].next == "wrapup", (
            f"{label}: closing without landing still goes through wrapup, "
            "which is where created issues are settled"
        )


def test_closing_without_landing_leaves_the_work_in_somebody_s_hands():
    for label, wf in _layers():
        rules = _prose(wf.steps["landing-declined-hold"].instructions)
        assert "HOLD:" in rules
        assert "닫지 않는다" in rules, (
            f"{label}: nothing merged, so the issue has no right to be closed"
        )
        assert "--labels handoff" in rules
        assert "브랜치 이름·tip" in rules, (
            f"{label}: the handoff spec must name the branch, which is the "
            "only link from the next person to the commits already made"
        )


# --------------------------------------------------------------------------- #
# the layer above it
# --------------------------------------------------------------------------- #
def test_the_remote_variant_inherits_both_edges():
    """``improv-worker-remote`` overrides only ``await-landing``'s title, so
    the new options must reach it unchanged -- a PR that nobody merges is the
    same silence with a different medium."""
    remote = state_mod.load_bundled("improv-worker-remote")
    wait = remote.steps["await-landing"].select
    assert wait.options["nudge"].interval == NUDGE_INTERVAL
    assert wait.options["nudge"].next == "landing-nudge"
    assert wait.options["declined"].next == "landing-declined"
    assert remote.steps["landing-nudge"].next == "await-landing"
    assert remote.steps["rework-gate"].next == "work"
    # The reminder line carries the PR url the remote overlay writes.
    assert "PR url" in _prose(remote.steps["landing-nudge"].instructions)


def test_the_loop_stays_inside_the_engine_s_visit_budget():
    """The backstop is ``max_visits``: past it the run parks in front of a
    person (``waiting_approval``, ``reason: loop_limit``) instead of nudging
    for ever. At ten minutes a pass that is about four hours of silence."""
    for label, wf in _layers():
        assert wf.max_visits == model.DEFAULT_MAX_VISITS, (
            f"{label}: the nudge loop is sized against the default budget; "
            "raising it here would also raise every other loop in the file"
        )


# --------------------------------------------------------------------------- #
# fixtures for the behavioural half
# --------------------------------------------------------------------------- #
WAITER = """
name: waiter
steps:
  wait:
    select:
      prompt: has the parent answered?
      chooser: agent
      options:
        landed: {description: merged, next: landed}
        nudge: {description: remind the parent, next: nudge-step, interval: 600}
  nudge-step:
    instructions: send one line
    next: wait
  landed:
    instructions: confirm the merge
"""

T0 = datetime(2026, 9, 17, 2, 0, tzinfo=timezone.utc)


@pytest.fixture
def proj_wait(home, tmp_path, monkeypatch):
    d = tmp_path / "proj"
    (d / ".claunch" / "workflows").mkdir(parents=True)
    (d / ".claunch" / "workflows" / "waiter.yaml").write_text(WAITER, encoding="utf-8")
    monkeypatch.chdir(d)
    monkeypatch.delenv(state_mod.SESSION_ENV, raising=False)
    return d


@pytest.fixture
def clock(monkeypatch):
    now = {"at": T0}
    monkeypatch.setattr(engine, "_utc_now", lambda: now["at"])

    def advance(seconds: float = 0) -> datetime:
        now["at"] = now["at"] + timedelta(seconds=seconds)
        return now["at"]

    return advance
