@echo off
rem ============================================================
rem  claunch shim  --  generated by stubs/install-shim.ps1
rem
rem  Forwards every `claunch ...` call to a checkout of this repo:
rem      uv run --project <repo> claunch ...
rem  Source edits apply on the next invocation, so there is nothing
rem  to reinstall after editing the launcher.
rem
rem  Re-run stubs/install-shim.ps1 after moving the repo, or set
rem  CLAUNCH_PROJECT in your environment to override the path.
rem ============================================================
setlocal
if not defined CLAUNCH_PROJECT set "CLAUNCH_PROJECT=__CLAUNCH_PROJECT__"
set "CLAUNCH_UV_FLAGS=__UV_FLAGS__"
uv run%CLAUNCH_UV_FLAGS% --project "%CLAUNCH_PROJECT%" claunch %*
exit /b %ERRORLEVEL%
