<#
.SYNOPSIS
    Install the `claunch` shim into a directory on PATH.

.DESCRIPTION
    Renders stubs/claunch.bat into <BinDir>\claunch.bat with this checkout's
    absolute path baked in. The shim runs the launcher straight from source via
    `uv run --project <repo> claunch ...`, so edits to the repo take effect on
    the next invocation and there is never anything to reinstall.

    This replaces `uv tool install --editable .`, which keeps a separate tool
    venv that can drift or break.

.PARAMETER BinDir
    Where to write claunch.bat. Defaults to $env:CLAUNCH_BIN_DIR, else
    ~\.local\bin (the directory uv puts its own tool executables in).

.PARAMETER ProjectDir
    The claude-launcher checkout to point at. Defaults to this script's parent.

.PARAMETER NoSync
    Bake `--no-sync` into the shim. Skips uv's per-call environment sync for a
    faster start; you must then run `uv sync` yourself when dependencies change.

.PARAMETER AddToPath
    Append BinDir to the *user* PATH (persisted) if it is not already there.

.PARAMETER Force
    Overwrite a claunch.bat this script did not generate, and delete a
    conflicting claunch.exe/claunch.cmd in BinDir.

.PARAMETER Uninstall
    Remove the generated shim instead of installing it.

.EXAMPLE
    pwsh -File stubs\install-shim.ps1

.EXAMPLE
    pwsh -File stubs\install-shim.ps1 -BinDir D:\bin -NoSync -AddToPath
#>
[CmdletBinding()]
param(
    [string]$BinDir,
    [string]$ProjectDir,
    [switch]$NoSync,
    [switch]$AddToPath,
    [switch]$Force,
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Every file we generate carries this line, so we can tell our own shim apart
# from an unrelated claunch.bat the user may have put there.
$marker = 'generated by stubs/install-shim.ps1'

function Write-Step($msg) { Write-Host "  $msg" }
function Write-Warn($msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }

function Write-AsciiCrlf([string]$Path, [string]$Text) {
    # cmd.exe mis-parses a leading UTF-8 BOM, and Windows PowerShell 5.1's
    # Out-File defaults to UTF-16. Write the bytes ourselves.
    $normalized = $Text -replace "`r?`n", "`r`n"
    [System.IO.File]::WriteAllText($Path, $normalized, (New-Object System.Text.UTF8Encoding($false)))
}

# ---------------------------------------------------------------- locations --

if (-not $ProjectDir) { $ProjectDir = Split-Path -Parent $PSScriptRoot }
if (-not $BinDir) {
    $BinDir = if ($env:CLAUNCH_BIN_DIR) { $env:CLAUNCH_BIN_DIR }
              else { Join-Path $env:USERPROFILE '.local\bin' }
}

$target = Join-Path $BinDir 'claunch.bat'

# ---------------------------------------------------------------- uninstall --

if ($Uninstall) {
    if (-not (Test-Path -LiteralPath $target)) {
        Write-Host "Nothing to remove: $target does not exist."
        exit 0
    }
    if ((Get-Content -LiteralPath $target -Raw) -notmatch [regex]::Escape($marker) -and -not $Force) {
        throw "$target was not generated by this script. Re-run with -Force to delete it anyway."
    }
    Remove-Item -LiteralPath $target -Force
    Write-Host "Removed $target"
    exit 0
}

# ------------------------------------------------------------ prerequisites --

$template = Join-Path $PSScriptRoot 'claunch.bat'
if (-not (Test-Path -LiteralPath $template)) { throw "Shim template not found: $template" }

$ProjectDir = (Resolve-Path -LiteralPath $ProjectDir).Path.TrimEnd('\')
if (-not (Test-Path -LiteralPath (Join-Path $ProjectDir 'pyproject.toml'))) {
    throw "$ProjectDir is not a claude-launcher checkout (no pyproject.toml)."
}

$uv = Get-Command uv -CommandType Application -ErrorAction SilentlyContinue
if (-not $uv) { throw "uv is not on PATH. Install it first: https://docs.astral.sh/uv/" }

Write-Host "Installing claunch shim"
Write-Step "project : $ProjectDir"
Write-Step "uv      : $($uv.Source)"
Write-Step "bin dir : $BinDir"

# --------------------------------------------------------------- conflicts --

# Within one directory, PATHEXT resolves .EXE before .BAT, so a leftover
# console-script executable would silently keep winning over the shim.
foreach ($ext in @('exe', 'cmd')) {
    $conflict = Join-Path $BinDir "claunch.$ext"
    if (Test-Path -LiteralPath $conflict) {
        if ($Force) {
            Remove-Item -LiteralPath $conflict -Force
            Write-Step "removed conflicting $conflict"
        } else {
            throw ("$conflict would shadow the shim (PATHEXT resolves .$ext first). " +
                   "Run ``uv tool uninstall claude-launcher``, or re-run with -Force to delete it.")
        }
    }
}

if ((Test-Path -LiteralPath $target) -and -not $Force) {
    if ((Get-Content -LiteralPath $target -Raw) -notmatch [regex]::Escape($marker)) {
        throw "$target already exists and was not generated by this script. Re-run with -Force to overwrite."
    }
}

# ------------------------------------------------------------------ render --

$uvFlags = if ($NoSync) { ' --no-sync' } else { '' }
$content = (Get-Content -LiteralPath $template -Raw).
    Replace('__CLAUNCH_PROJECT__', $ProjectDir).
    Replace('__UV_FLAGS__', $uvFlags)

if ($content -match '__[A-Z_]+__') {
    throw "Unsubstituted placeholder left in the rendered shim: $($Matches[0])"
}

if (-not (Test-Path -LiteralPath $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
    Write-Step "created $BinDir"
}

Write-AsciiCrlf -Path $target -Text $content
Write-Step "wrote   : $target$(if ($NoSync) { '  (--no-sync)' })"

# -------------------------------------------------------------------- PATH --

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (-not $userPath) { $userPath = '' }
$onUserPath = ($userPath -split ';' | Where-Object { $_ } |
               ForEach-Object { $_.TrimEnd('\') }) -contains $BinDir.TrimEnd('\')

if (-not $onUserPath) {
    if ($AddToPath) {
        [Environment]::SetEnvironmentVariable('Path', "$($userPath.TrimEnd(';'));$BinDir", 'User')
        $env:PATH = "$env:PATH;$BinDir"
        Write-Step "added $BinDir to the user PATH (new shells pick it up)"
    } else {
        Write-Warn "$BinDir is not on the user PATH. Re-run with -AddToPath, or add it yourself."
    }
}

# ------------------------------------------------------------------ verify --

$resolved = Get-Command claunch -ErrorAction SilentlyContinue
if ($resolved -and $resolved.Source -ne $target) {
    Write-Warn "``claunch`` currently resolves to $($resolved.Source) -- an earlier PATH entry wins over the shim."
}

$version = & $target --version 2>&1 | Out-String
if ($LASTEXITCODE -ne 0) {
    Write-Warn "Shim installed but ``claunch --version`` exited $LASTEXITCODE :"
    Write-Host $version
    exit 1
}
Write-Step "verified: $($version.Trim())"
Write-Host "Done. Open a new shell if PATH changed."
